# These are supported funding model platforms

github: [likhonsex]
# patreon: # Replace with your Patreon username
# open_collective: # Replace with your Open Collective username
# ko_fi: # Replace with your Ko-fi username
# tidelift: # Replace with your Tidelift package info
# community_bridge: # Replace with your Community Bridge info
# liberapay: # Replace with your Liberapay username
# issuehunt: # Replace with your IssueHunt username
# lfx_crowdfunding: # Replace with your LFX info
# polar: # Replace with your Polar info
custom: # Replace with up to 4 custom sponsorship URLs
  # - https://www.buymeacoffee.com/username
  # - https://www.paypal.me/username
